default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photo_galleria_development

test:
  <<: *default
  database: photo_galleria_test

production:
  <<: *default
  database: photo_galleria_production
  username: photo_galleria
  password: <%= ENV['PHOTO_GALLERIA_DATABASE_PASSWORD'] %>